from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from kaggle_research_agent import simple_yaml


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--score", type=float, default=0.81)
    args = parser.parse_args()

    config = simple_yaml.load(args.config, default={})
    model_type = config.get("model", {}).get("type", "unknown")
    score = _score_from_config(args.score, config)

    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    trial_id = output.name
    metrics = {
        "trial_id": trial_id,
        "cv_score": score,
        "lb_score": None,
        "objective": "maximize",
        "seed": config.get("cv", {}).get("seed", 42),
        "model_type": model_type,
        "prediction_correlation_with_best": None,
        "notes": _notes_for_config(model_type, config),
    }
    (output / "metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    print(f"Wrote {output / 'metrics.json'}")
    return 0


def _score_from_config(base_score: float, config: dict) -> float:
    score = base_score
    model_type = config.get("model", {}).get("type")
    features = config.get("features", {})
    if model_type == "skeleton_transformer":
        score += 0.015
    elif model_type in {"catboost", "xgboost", "tabular_nn"}:
        score += 0.005
    if features.get("use_view_aware_features"):
        score += 0.003
    if features.get("use_bed_wandering_aux_head"):
        score += 0.002
    return round(score, 6)


def _notes_for_config(model_type: str, config: dict) -> str:
    features = config.get("features", {})
    active = [key for key, value in features.items() if value is True]
    return (
        "Generated by scripts/demo_train.py for local runner verification. "
        f"model_type={model_type}; active_features={','.join(active) or 'none'}."
    )


if __name__ == "__main__":
    raise SystemExit(main())
